<?php

namespace ContainerHtHw79I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_BPAGgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.B_pA_Gg' shared service.
     *
     * @return \http\Env\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\DefaultController::convertMoney()": the $request argument is type-hinted with the non-existent class or interface: "http\\Env\\Request".');
    }
}
