<?php

namespace ContainerHtHw79I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrizeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qAdwjyt.App\Entity\Prize' shared service.
     *
     * @return \App\Entity\Prize
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.qAdwjyt": it references class "App\\Entity\\Prize" but no such service exists.');
    }
}
