<?php

namespace ContainerHtHw79I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\SendCommand' shared autowired service.
     *
     * @return \App\Command\SendCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/SendCommand.php';

        $container->privates['App\\Command\\SendCommand'] = $instance = new \App\Command\SendCommand(($container->privates['App\\Service\\PrizeService'] ?? $container->load('getPrizeServiceService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setName('app:convert');

        return $instance;
    }
}
