<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHtHw79I\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHtHw79I/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHtHw79I.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHtHw79I\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHtHw79I\App_KernelDevDebugContainer([
    'container.build_hash' => 'HtHw79I',
    'container.build_id' => 'eec21371',
    'container.build_time' => 1604941723,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHtHw79I');
